name = axelor-stock
mavenGroup = com.axelor.apps
version = 9.0.4

title = DPX Stock
description = DPX Stock Module

depends = axelor-core, axelor-web, axelor-utils, axelor-message, axelor-studio, axelor-base
depends.maven = com.axelor:axelor-core, com.axelor:axelor-web, com.axelor.addons:axelor-utils, com.axelor.addons:axelor-message, com.axelor.addons:axelor-studio, com.axelor.apps:axelor-base
